language: php
services:
  - docker

install:
  - echo $(pwd)
  - |
    git clone --branch production https://git.drupalcode.org/project/drupalci_testbot.git ../drupalci_testbot
    cd ../drupalci_testbot
    composer install
script:
  - ./drupalci run .travisci/drupalci.yml

