language: php
services:
  - docker

install:
  - |
    git clone --branch production https://git.drupalcode.org/project/drupalci_testbot.git ../drupalci_testbot
    cd ../drupalci_testbot
    composer install --prefer-dist --no-suggest --no-interaction --no-dev
script:
  - DCI_Composer_Branch=$TRAVIS_BRANCH ./drupalci run ../commerce_api/.travisci/drupalci.yml

