<?php

/**
 * @file
 * Provides hooks.
 */

use Drupal\commerce_api\Plugin\Field\ComputedOrderTotal;
use Drupal\commerce_api\Plugin\Field\ComputedResolvedPrice;
use Drupal\commerce_api\Plugin\openapi\OpenApiGenerator\AdjustedJsonApiGenerator;
use Drupal\commerce_cart\CartSessionInterface;
use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_order\Entity\OrderItemInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_field_access().
 */
function commerce_api_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $field_access = \Drupal::getContainer()->get('commerce_api.field_access');
  return $field_access->handle($operation, $field_definition, $account, $items);
}

/**
 * Implements hook_entity_access().
 *
 * Allows anonymous users to view their own orders without
 * granting the `view own commerce_order` permission.
 *
 * @todo decide about UPDATE and DELETE.
 *       ideally UPDATE would be handled on field level.
 */
function commerce_api_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity instanceof OrderInterface || $entity instanceof OrderItemInterface) {
    if ($entity instanceof OrderItemInterface) {
      $order_id = $entity->getOrderId();
    }
    else {
      $order_id = $entity->id();
    }

    $cart_session = \Drupal::getContainer()->get('commerce_cart.cart_session');
    assert($cart_session instanceof CartSessionInterface);

    // Active carts may be modified.
    $active_cart = $cart_session->hasCartId($order_id, CartSessionInterface::ACTIVE);
    $completed_cart = $cart_session->hasCartId($order_id, CartSessionInterface::COMPLETED);
    if ($operation === 'view') {
     return AccessResult::allowedIf($active_cart || $completed_cart);
    }
    elseif ($operation === 'update') {
      return AccessResult::allowedIf($active_cart);
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function commerce_api_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  /** @var \Drupal\Core\Field\BaseFieldDefinition[] $fields */
  if ($entity_type->id() === 'commerce_order') {
    $fields['order_number']->setRequired(FALSE);
    $fields['billing_profile']->setRequired(TRUE);

    if (isset($fields['payment_gateway'])) {
      // @todo add a constraint which marks it required if order total > 0;
    }
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function commerce_api_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'commerce_order') {
    // @todo needs a test.
    $fields['order_total'] = BaseFieldDefinition::create('map')
      ->setLabel(t('Order total'))
      ->setReadOnly(TRUE)
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setClass(ComputedOrderTotal::class);
    return $fields;
  }
  if ($entity_type->id() === 'commerce_product_variation') {
    // @todo needs a test.
    $fields['resolved_price'] = BaseFieldDefinition::create('commerce_price')
      ->setLabel(t('Resolved price'))
      ->setReadOnly(TRUE)
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setSetting('source_field', 'price')
      ->setClass(ComputedResolvedPrice::class);
    return $fields;
  }

  return [];
}

/**
 * Implements hook_openapi_generator_alter().
 *
 * Prevents Cart API resources from crashing OpenAPI.
 */
function commerce_api_openapi_generator_alter(array &$definitions) {
  if (isset($definitions['jsonapi'])) {
    $definitions['jsonapi']['class'] = AdjustedJsonApiGenerator::class;
  }
}

