version: 2.1
commands:
  setup-job:
    steps:
      - run: sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg62-turbo-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd bcmath
      - checkout
      - restore_cache:
          keys:
            - v-composer-cache
      - run: composer global require hirak/prestissimo:^0.3
  save-cache:
    steps:
      - save_cache:
          key: v-composer-cache
          paths:
            - ~/.composer/cache
  create-drupal-project:
    steps:
      - run: composer create-project drupal/recommended-project:^8.8@alpha /tmp/drupal --no-interaction --prefer-dist --ignore-platform-reqs
  local-require:
    steps:
      - run:
          name: Add as local
          command: |
            cd /tmp/drupal
            composer config repositories.1 path ${CIRCLE_WORKING_DIRECTORY}
            composer require drupal/commerce_api "*"
            cat composer.json
jobs:
  test:
    docker:
      - image: circleci/php:7.2-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install DrupalCI
          command: |
            cd ..
            git clone --branch production https://git.drupalcode.org/project/drupalci_testbot.git
            mv commerce_api drupalci_testbot/commerce_api
            cd drupalci_testbot
            composer install --prefer-dist --no-suggest --no-interaction --no-dev
      - run: DCI_Composer_Branch=$CIRCLE_BRANCH ./drupalci run commerce_api/.travisci/drupalci.yml

workflows:
  version: 2
  test:
    jobs:
      - test
