build:
  environment:
    startcontainers:
      runcontainers:
        phpversion: 'php-7.1-apache:production'
    create_db:
      dbcreate: {  }
    db-type: mysql
    db-version: '5.5'
    dbhost: ''
    dbuser: drupaltestbot
    dbpassword: drupaltestbotpw
  codebase:
    assemble_codebase:
      checkout_core:
        repositories:
          -
            repo: 'https://git.drupalcode.org/project/drupal.git'
            branch: 8.8.x
      composer.core_install:
        phpversion: 7.1.14
        options: 'install --prefer-dist --no-suggest --no-interaction --no-progress'
        halt-on-fail: true
      composer_contrib:
        project: commerce_api
        branch: "*"
      update_build: {  }
      update_dependencies: {  }
    project-name: commerce_api
    project-type: module
    project-subdir: ''
  assessment:
    validate_codebase:
      phplint: {  }
      container_composer: {  }
      phpcs:
        sniff-all-files: true
        halt-on-fail: false
        coder-version: ^8.2@stable
    testing:
      run_tests.standard:
        types: 'PHPUnit-Unit,PHPUnit-Kernel,PHPUnit-Functional'
        testgroups: '--all'
        suppress-deprecations: false
        color: true
        die-on-fail: false
        keep-results: true
        keep-results-table: false
        verbose: false
        concurrency: 0
        halt-on-fail: false
        repeat: 1
      run_tests.javascript:
        concurrency: 1
        types: PHPUnit-FunctionalJavascript
        testgroups: '--all'
        suppress-deprecations: false
        halt-on-fail: false
        color: true
        die-on-fail: false
        keep-results: true
        keep-results-table: false
        verbose: false
        repeat: 1
